title: Assessing the validity of a calcifying oral biofilm model as a suitable proxy for dental calculus
project:
  type: default
  output-dir: _output
  execute-dir: project
  #pre-render: _bib.R # only works when main author renders
format: 
  arxiv-pdf:
    output-file: "bioRxiv-manuscript-2.1"
    keep-tex: true
    linenumbers: false
    doublespacing: false
    runninghead: "Validity of a calcifying oral biofilm model"
  html:
    keep-md: true
  pdf:
    keep-tex: true
    output-file: "draft-manuscript_v1"
    documentclass: article
    link-citations: true
    geometry:
      - top=30mm
      - left=30mm
      - heightrounded
    include-in-header: 
      text: |
        \linenumbers
        \setlength{\parindent}{15pt}
  docx: 
    output-file: "bioRxiv-manuscript-2.1"
execute: 
  freeze: auto
  echo: false
  warning: false
knitr:
  opts_chunk: 
    message: false
    fig-align: "center"
    fig-path: "figures/"
author: 
  - name: Bjørn Peare Bartholdy
    email: b.p.bartholdy@arch.leidenuniv.nl
    orcid: 0000-0003-3985-1016
    corresponding: true
    affiliations:
      - ref: leiden
  - name: Irina M. Velsko
    orcid: 0000-0001-9810-9917
    affiliations:
      - ref: mpi
  - name: Shira Gur-Arieh
    orcid: 0000-0003-2015-7817
    affiliations:
      - ref: haifa
      - ref: kiel
  - name: Zandra Fagernäs
    orcid: 0000-0003-2667-3556
    affiliations:
      - ref: mpi
      - ref: globe
  - name: Christina Warinner
    orcid: 0000-0002-4528-5877
    affiliations:
      - ref: harv
      - ref: mpi
  - name: Amanda G. Henry
    orcid: 0000-0002-2923-4199
    affiliations:
      - ref: leiden
affiliations:
  - id: leiden
    name: Leiden University
    department: Faculty of Archaeology
    city: Leiden
    country: The Netherlands
  - id: mpi
    name: Max Planck Institute for Evolutionary Anthropology
    department: Department of Archaeogenetics
    city: Leipzig
    country: Germany
  - id: globe
    name: University of Copenhagen
    department: Globe Institute
    city: Copenhagen
    country: Denmark
  - id: haifa
    name: University of Haifa
    department: The Leon Recanati Institute for Maritime Studies
    city: Haifa
    country: Israel
  - id: kiel
    name: University of Kiel
    department: Institute of Pre- and Protohistoric Archaeology
    city: Kiel
    country: Germany
  - id: harv
    name: Department of Anthropology, Harvard University
    department: Department of Anthropology
    city: Cambridge, MA
    country: USA
  - id: naturalis
    name: Naturalis Biodiversity Center
    department: Tropical Botany Group
    city: Leiden
    country: The Netherlands
bibliography: references.bib
csl: apa.csl
keywords:
  - oral biofilm
  - dental calculus
  - microbiome
  - metagenomics
  - ftir
abstract-title: Abstract
abstract: |
  Dental calculus is increasingly used by researchers to study dietary patterns
  in past populations. The benefits of using dental calculus for this purpose
  have been clearly demonstrated in previous studies, with dental calculus
  harbouring a wealth of microremains and biomarkers for health and diet
  within its mineral matrix.
  Previous studies have demonstrated some of the limitations and
  biases of how methods of processing may overlook, or even remove,
  some of the important information contained within the mineralised matrix.
  However, there are many factors that are
  impossible to account for *in vivo* and in archaeological material, such as
  exact dietary intake, and individual factors such as pH and enzyme activity,
  leaving some limitations that may not be addressed through these types of studies
  and will require a different approach.  
  
  We present a protocol for creating a calcifying oral biofilm model
  that can be used to explore the biases and
  limitations of dental calculus as a medium for paleodietary reconstructions.
  We report the microbial and mineral composition of our model in an effort to
  validate the model calculus as an appropriate proxy to natural dental calculus.
  The microbial profile and species diversity of our model was determined using
  metagenomic classification with the nf-core/eager pipeline and Kraken2, and
  compared to various reference samples from oral sites, including
  saliva, plaque, and dental calculus. We then
  assessed whether our model calculus mineralises in a manner similar to natural
  dental calculus using Fourier transform infrared (FTIR) spectroscopy.
  The metagenomic classification showed a microbial
  profile predominantly made up of (facultative) anaerobes, with a community
  structure that was somewhat distinct from other oral reference samples.
  The core genera of the model consisted of oral species, but clustered
  separately from oral reference samples, with a higher abundance of anaerobes.  
  Mineral and organic components of our model mimic that of the modern and archaeological
  reference calculus that was used as a comparison. There was an overall increase
  in the inorganic component relative to
  organic over the course of the experiment, with carbonated hydroxyapatite as
  the principal compound, consistent with natural human-derived calculus.
  
  We conclude that oral biofilm models, such as the one presented in this study,
  have great potential to validate current methods used in the analysis of archaeological
  dental calculus, and should be used to complement, rather than replace current
  *in vivo* studies.
