project:
  type: default
  output-dir: _output
  execute-dir: project
  pre-render: _bib.R
execute: 
  freeze: true
title: Assessing the validity of a mineralised oral biofilm model as a suitable proxy for dental calculus
author: 
  - name: Bjørn Peare Bartholdy
    orcid: 0000-0003-3985-1016
    corresponding: true
    affiliations:
    - ref: leiden
  - name: Irina M. Velsko
    affiliations:
    - ref: mpi
  - name: Shira Gur-Arieh
    affiliations: Haifa University
  - name: Zandra Fagernäs
    affiliations:
    - ref: mpi
  - name: Sophie Seng
    affiliations:
    - ref: mpi
  - name: Amanda G. Henry
    affiliations:
    - ref: leiden
affiliations:
  - id: leiden
    name: Leiden University
    city: Leiden
  - id: mpi
    name: Max Planck Institute for Evolutionary Anthropology
    city: Leipzig
bibliography: references.bib
csl: apa.csl
abstract-title: Abstract
abstract: |
  This is the abstract for the paper.
format: 
  html:
    keep-md: true
  pdf:
    keep-tex: true
    documentclass: article
    geometry:
      - top=30mm
      - left=30mm
      - heightrounded
    include-in-header: 
      text: |
        \usepackage{lineno}
        \linenumbers
