project:
  type: default
  output-dir: 07-publications/_output
title: TBD
author: |
  B.P. Bartholdy, I. Velsko, S. Gur-Arieh, Z. Fagernäs, S. Seng, A.G. Henry
citation-location: document
bibliography: references.bib
abstract-title: Abstract
abstract: |
  This is the abstract for the paper.
format: 
  html:
    keep-md: true
  pdf:
    keep-tex: true
    documentclass: article
