project:
  type: default
  output-dir: _output
  execute-dir: project
  pre-render: _bib.R
execute: 
  freeze: true
title: TBD
author: 
  -name: B.P. Bartholdy
  -name: I. Velsko
  -name: S. Gur-Arieh
  -name: Z. Fagernäs
  -name: S. Seng
  -name: A.G. Henry
citation-location: document
bibliography: references.bib
abstract-title: Abstract
abstract: |
  This is the abstract for the paper.
format: 
  html:
    keep-md: true
  pdf:
    keep-tex: true
    documentclass: article
