---
title: cuperdec results
output: pdf_document
---

```{r setup, include=FALSE}
library(cuperdec)
library(here)
library(tidyverse)
# source("02-scripts/authentication.R")
kraken_taxatab <- readr::read_csv(here("03-data/taxa_table.csv"))
metadata <- readr::read_csv(here("03-data/sample_metadata.csv"))
file_names <- list.files(here("03-data/kraken/"), "_report")
sample_names <- gsub(".unmapped.*", "", file_names)

metadata$sample[-1] <- paste0(metadata$sample[-1], "0101") # match metadata names to sequence names
metadata <- subset(metadata, metadata$sample %in% sample_names) # subset successful sequences (?)
```

```{r}
head(kraken_taxatab) %>%
  select(1:5) %>%
  knitr::kable()
```

```{r}
head(metadata) %>%
  select(sample, source) %>%
  knitr::kable()
```

```{r}
taxa_table <- load_taxa_table(kraken_taxatab)
iso_database <- load_database(cuperdec_database_ex, target = "oral")
metadata_table <- load_map(metadata,
                           sample_col = "sample",
                           source_col = "source"
                           )

curves <- calculate_curve(taxa_table, iso_database)
filter_result <- simple_filter(curves, 60)
```


```{r}
plot_cuperdec(curves, metadata_table, filter_result)
```

